---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

luksGeneration: luks2

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true

initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs
  - f2fs

# Keep in sync with requiredStorage in welcome.conf.
requiredStorage: 25
