---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - wheel
  - audio
  - video
  - storage
  - input
  - lp
  - network

sudoersGroup: wheel
sudoersConfigureWithGroup: false

# No root login: the first user administers the box through sudo.
setRootPassword: false
doReusePassword: false

displayAutologin: true
doAutologin: false

passwordRequirements:
  minLength: 6
  maxLength: -1
  libpwquality:
    - minlen=6
    - minclass=0
allowWeakPasswords: true
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root, live, rescue ]
  home_permissions: "o700"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "synapseos"
  forbidden_names: [ localhost ]
