# SynapseOS — Catppuccin Macchiato, no chrome, frosted even when focused.
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0
disable_ligatures never

include macchiato.conf

background_opacity 0.78
background_blur 32
dynamic_background_opacity yes
window_padding_width 12
window_margin_width 0
confirm_os_window_close 0
enable_audio_bell no
window_alert_on_bell no
remember_window_size yes
hide_window_decorations no
linux_display_server wayland
shell_integration enabled
term xterm-kitty
cursor_shape beam
cursor_blink_interval 0.6
url_style curly
copy_on_select clipboard
strip_trailing_spaces smart
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
